/**
 * Compiles the DTCG token JSON in ./tokens into:
 *  - src/generated/tokens.css  CSS custom properties (light default, dark via media query or data-theme)
 *  - src/generated/tokens.ts   typed raw values + `var(--…)` references for TS/D3 consumers
 *
 * Style Dictionary resolves references ({palette.purple.600}) and names; we own the output
 * format because we need theme blocks, reduced-motion overrides and spring triplets.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import StyleDictionary from "style-dictionary";

const here = import.meta.dir;
const THEMES = ["light", "dark"] as const;
type Theme = (typeof THEMES)[number];

interface Token {
  readonly name: string;
  readonly path: readonly string[];
  readonly value: unknown;
  readonly type: string | undefined;
  readonly themed: boolean;
}

const resolveTheme = async (theme: Theme): Promise<readonly Token[]> => {
  const sd = new StyleDictionary({
    source: [join(here, "tokens/base/*.json"), join(here, `tokens/themes/${theme}.json`)],
    platforms: { css: { transforms: ["name/kebab"] } },
    log: { verbosity: "silent", warnings: "disabled" },
  });
  const { allTokens } = await sd.getPlatformTokens("css");
  return allTokens
    .filter((t) => t.path[0] !== "palette") // palette is private: only semantic tokens ship
    .map((t) => ({
      name: t.name,
      path: t.path,
      value: t.$value ?? t.value,
      type: t.$type ?? t.type,
      themed: (t.filePath ?? "").includes("/themes/"),
    }));
};

const quoteFont = (f: string) => (/\s/.test(f) ? `"${f}"` : f);

/** One token can expand to several CSS properties (springs → stiffness/damping/mass). */
const cssDecls = (t: Token): readonly (readonly [string, string])[] => {
  const v = t.value;
  if (t.type === "fontFamily" && Array.isArray(v))
    return [[t.name, v.map(String).map(quoteFont).join(", ")]];
  if (t.type === "cubicBezier" && Array.isArray(v))
    return [[t.name, `cubic-bezier(${v.join(", ")})`]];
  if (t.type === "spring" && typeof v === "object" && v !== null)
    return Object.entries(v).map(([k, n]) => [`${t.name}-${k}`, String(n)] as const);
  return [[t.name, String(v)]];
};

const block = (
  selector: string,
  tokens: readonly Token[],
  extra: readonly string[] = [],
  indent = "",
) =>
  [
    `${indent}${selector} {`,
    ...extra.map((e) => `${indent}  ${e}`),
    ...tokens.flatMap(cssDecls).map(([n, v]) => `${indent}  --${n}: ${v};`),
    `${indent}}`,
  ].join("\n");

const camel = (s: string) => s.replace(/-([a-z0-9])/g, (_, c: string) => c.toUpperCase());

/** Raw TS values: durations and breakpoints become numbers so JS can compute with them. */
const tsValue = (t: Token): unknown => {
  if (typeof t.value === "string" && t.type === "duration") return Number.parseFloat(t.value);
  if (typeof t.value === "string" && t.path[0] === "breakpoint") return Number.parseFloat(t.value);
  return t.value;
};

type Tree = { readonly [key: string]: unknown };

/** Immutable insert of `value` at `keys` into a nested tree. */
const setIn = (tree: Tree, [head, ...rest]: readonly string[], value: unknown): Tree => {
  if (head === undefined) return tree;
  const child = tree[head];
  return {
    ...tree,
    [head]:
      rest.length === 0
        ? value
        : setIn(typeof child === "object" && child !== null ? (child as Tree) : {}, rest, value),
  };
};

const nest = (tokens: readonly Token[], leaf: (t: Token) => unknown): Tree =>
  tokens.reduce<Tree>((tree, t) => setIn(tree, t.path.map(camel), leaf(t)), {});

const cssVarLeaf = (t: Token): unknown =>
  t.type === "spring"
    ? Object.fromEntries(Object.keys(t.value as object).map((k) => [k, `var(--${t.name}-${k})`]))
    : `var(--${t.name})`;

const [light, dark] = await Promise.all(THEMES.map(resolveTheme));
if (light === undefined || dark === undefined) throw new Error("theme resolution failed");

const base = light.filter((t) => !t.themed);
const lightThemed = light.filter((t) => t.themed);
const darkThemed = dark.filter((t) => t.themed);
const durations = base.filter(
  (t) => t.path[0] === "motion" && t.path[1] === "duration" && t.path[2] !== "instant",
);

const banner =
  "/* Generated by packages/tokens/build.ts — do not edit. Edit tokens/*.json and run `bun run build`. */";
const css = [
  banner,
  block(":root", [...base, ...lightThemed], ["color-scheme: light;"]),
  "@media (prefers-color-scheme: dark) {",
  block(':root:not([data-theme="light"])', darkThemed, ["color-scheme: dark;"], "  "),
  "}",
  block(':root[data-theme="dark"]', darkThemed, ["color-scheme: dark;"]),
  "/* Reduced motion: every duration collapses so state changes are instant but still happen. */",
  "@media (prefers-reduced-motion: reduce) {",
  `  :root {\n${durations.map((t) => `    --${t.name}: 0ms;`).join("\n")}\n  }`,
  "}",
  "",
].join("\n");

const json = (v: unknown) => JSON.stringify(v, null, 2);
const ts = [
  banner,
  "",
  "/** Raw token values (theme-independent). Durations are ms numbers, breakpoints px numbers. */",
  `export const tokens = ${json(nest(base, tsValue))} as const;`,
  "",
  "/** Raw themed values per theme. Prefer `vars` in UI so the active theme applies automatically. */",
  `export const themes = ${json({ light: nest(lightThemed, tsValue), dark: nest(darkThemed, tsValue) })} as const;`,
  "",
  "/** `var(--…)` references for every token, for inline styles, SVG attributes and D3. */",
  `export const vars = ${json(nest([...base, ...lightThemed], cssVarLeaf))} as const;`,
  "",
  "/** Every CSS custom property name the stylesheet defines (without the leading `--`). */",
  `export const cssVarNames = ${json([...base, ...lightThemed].flatMap(cssDecls).map(([n]) => n))} as const;`,
  "",
].join("\n");

mkdirSync(join(here, "src/generated"), { recursive: true });
writeFileSync(join(here, "src/generated/tokens.css"), css);
writeFileSync(join(here, "src/generated/tokens.ts"), ts);
console.log(`tokens: ${base.length} base, ${lightThemed.length} themed`);
