/**
 * @nostrschool/fixtures — deterministic personas, relays and REAL signed events.
 *
 * Events in `src/data/events.json` are generated by `bun run scripts/generate.ts` (fixed keys,
 * nonces, timestamps and BIP-340 aux data), so they verify and never change between runs.
 */
import {
  type Hex,
  type NostrEvent,
  type RelayUrl,
  unwrapGiftWrap,
  validateEventShape,
} from "@nostrschool/protocol";
import raw from "./data/events.json" with { type: "json" };
import { newestFirst, parseFixtureFile } from "./event-utils.ts";
import { getPersona, isPersonaId, PERSONAS, personaByPubkey } from "./personas.ts";
import type {
  FollowGraph,
  GiftWrapFixture,
  PersonaId,
  RelayListEntry,
  ZapFixture,
} from "./types.ts";

export type { FixtureError, FixtureErrorCode, FixtureFile } from "./event-utils.ts";
export { parseFixtureFile } from "./event-utils.ts";
export {
  deriveFixtureKey,
  FIXTURE_NOW,
  getPersona,
  isPersonaId,
  PERSONA_IDS,
  PERSONAS,
  personaByPubkey,
  ZAP_SERVICES,
  type ZapService,
} from "./personas.ts";
export { getRelay, RELAYS } from "./relays.ts";
export type * from "./types.ts";

const parsed = parseFixtureFile(raw);
// Committed data is part of the build: if it is corrupt, fail at import, loudly.
if (!parsed.ok) throw new Error(`@nostrschool/fixtures: ${parsed.error.message}`);
const FILE = parsed.value;

/** Every committed fixture event (all kinds), newest first. */
export const FIXTURE_EVENTS: readonly NostrEvent[] = [...FILE.events].sort(newestFirst);

const BY_ID = new Map(FIXTURE_EVENTS.map((e) => [e.id, e]));
const pubkeyOf = (who: PersonaId | Hex): Hex => (isPersonaId(who) ? getPersona(who).pubkey : who);

/** Events of one or several kinds, newest first. */
export const eventsByKind = (kind: number | readonly number[]): readonly NostrEvent[] => {
  const kinds: readonly number[] = typeof kind === "number" ? [kind] : kind;
  return FIXTURE_EVENTS.filter((e) => kinds.includes(e.kind));
};

/** Events authored by a persona (id) or pubkey, newest first. */
export const eventsByAuthor = (author: PersonaId | Hex): readonly NostrEvent[] => {
  const pubkey = pubkeyOf(author);
  return FIXTURE_EVENTS.filter((e) => e.pubkey === pubkey);
};

export const eventById = (id: Hex): NostrEvent | undefined => BY_ID.get(id);

/** Newest event of `kind` by `pubkey` — replaceable-event semantics (NIP-01). */
const latest = (kind: number, pubkey: Hex): NostrEvent | undefined =>
  FIXTURE_EVENTS.find((e) => e.kind === kind && e.pubkey === pubkey);

/** Who follows whom, derived from the latest kind 3 of each persona. */
export const followGraph = (): FollowGraph => ({
  nodes: PERSONAS.map((p) => ({ pubkey: p.pubkey, personaId: p.id })),
  edges: PERSONAS.flatMap((p) =>
    (latest(3, p.pubkey)?.tags ?? []).flatMap((t) =>
      t[0] === "p" && t[1] !== undefined ? [{ from: p.pubkey, to: t[1] }] : [],
    ),
  ),
});

/** NIP-65 relay list, derived from the latest kind 10002 event of a persona (id) or pubkey. */
export const relayListFor = (who: PersonaId | Hex): readonly RelayListEntry[] =>
  (latest(10002, pubkeyOf(who))?.tags ?? [])
    .filter((t) => t[0] === "r" && t[1] !== undefined)
    .map(([, url = "", marker]) => ({ url, read: marker !== "write", write: marker !== "read" }));

/** Events stored on a fake relay (from the committed placement map), newest first. */
export const eventsOnRelay = (url: RelayUrl): readonly NostrEvent[] =>
  FIXTURE_EVENTS.filter((e) => relaysForEvent(e.id).includes(url));

/** Relays that hold a given event (empty for events never sent to a relay, e.g. zap requests). */
export const relaysForEvent = (id: Hex): readonly RelayUrl[] => FILE.placement[id] ?? [];

const persona = (pubkey: Hex, what: string): PersonaId => {
  const p = personaByPubkey(pubkey);
  if (p === undefined) throw new Error(`@nostrschool/fixtures: ${what} ${pubkey} is not a persona`);
  return p.id;
};

let wrapCache: readonly GiftWrapFixture[] | undefined;

/**
 * The NIP-17 DM fixtures with every layer, oldest message first. Opened for real (NIP-44
 * decryption with the recipient's key) on first call, so seals and rumors are never stored.
 */
export const giftWraps = (): readonly GiftWrapFixture[] => {
  wrapCache ??= eventsByKind(1059)
    .map((wrap) => {
      const recipient = persona(wrap.tags.find((t) => t[0] === "p")?.[1] ?? "", "wrap recipient");
      const opened = unwrapGiftWrap(wrap, getPersona(recipient).secretKey);
      if (!opened.ok) throw new Error(`@nostrschool/fixtures: ${opened.error.message}`);
      const { seal, rumor } = opened.value;
      return { sender: persona(rumor.pubkey, "dm sender"), recipient, rumor, seal, wrap };
    })
    .sort((a, b) => a.rumor.created_at - b.rumor.created_at);
  return wrapCache;
};

/** The NIP-57 zap fixtures with request and receipt, newest first. */
export const zaps = (): readonly ZapFixture[] =>
  eventsByKind(9735).map((receipt) => {
    const tag = (e: NostrEvent, name: string): string =>
      e.tags.find((t) => t[0] === name)?.[1] ?? "";
    // The receipt embeds the exact request it pays for (NIP-57 `description` tag).
    const parsed = validateEventShape(JSON.parse(tag(receipt, "description")));
    if (!parsed.ok || parsed.value.kind !== 9734) {
      throw new Error(`@nostrschool/fixtures: receipt ${receipt.id} embeds no zap request`);
    }
    const request = parsed.value;
    return {
      sender: persona(request.pubkey, "zap sender"),
      recipient: persona(tag(receipt, "p"), "zap recipient"),
      amountMsats: Number(tag(request, "amount")),
      request,
      receipt,
      bolt11: tag(receipt, "bolt11"),
    };
  });
